<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <OutputType>WinExe</OutputType>
    <AssemblyName>MXH-VPS-Deploy</AssemblyName>
    <UseWinUI>true</UseWinUI>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../../assets/gui/app.ico</ApplicationIcon>
    <PublishSingleFile>false</PublishSingleFile>
    <DefineConstants>$(DefineConstants);DISABLE_XAML_GENERATED_MAIN</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Update="Microsoft.NETCore.App" RuntimeFrameworkVersion="10.0.12" />
    <ProjectReference Include="../Mxh.VpsDeploy.Windows/Mxh.VpsDeploy.Windows.csproj" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260804001" />
    <Content Include="../../assets/gui/app.ico" Link="assets/gui/app.ico" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../assets/gui/app.svg" Link="assets/gui/app.svg" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../assets/gui/fonts/*.ttf" Link="Fonts/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../assets/gui/fonts/*-OFL.txt" Link="Fonts/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
